import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import SiteLayout from '../components/layouts/site'

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SEO /> */}
      <SiteLayout>
        {/* banner */}
        <section className='container flex flex-col mx-auto'>
          <h1>Taking your wellness program to the <span> next level </span></h1>
          <p>Discover how our B2B beauty services can improve employee morale, productivity and help to attract new clients. Book your consultation today and see the difference for yourself!</p>
          <Link href='/services'>Pamper my team</Link>
        </section>

        {/* join these other companies */}
        <section className='container flex flex-col mx-auto gap-10'>
          <div className='flex flex-row items-center justify-between gap-5'>
            <p className='w-[12rem]'>Join the 64+ teams</p>
            <hr className='w-full border-black' />
          </div>

          <hr className='w-full border-black' />
        </section>
      </SiteLayout>
    </>
  );
};

export default Home;
